version: '3'

services:
   scrapyd:
     image: scrapyd:latest
     container_name: scrapyd
     env_file:
        - conf/scrapy.env
     restart: always

   reverse-proxy:
     image: nginx:alpine
     container_name: scrapyd-web
     env_file:
        - conf/scrapyd_web.env
     volumes:
       - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
       - "./conf/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro"
     depends_on:
       - scrapyd
     links:
       - scrapyd
     ports:
       - 80:80    
     restart: always   

   scrapoxy:
     image: scrapoxy_custom:latest
     env_file:
        - conf/scrapoxy.env
     container_name: scrapoxy
     volumes:
       - "./conf/scrapoxy.conf.json:/etc/scrapoxy/config.json:ro"
     links:
       - scrapyd
     ports:
       - 8888:8888
       - 8889:8889
     restart: always
         

