version: '3'

services:
   scrapyd:
     image: scrapyd
     
     container_name: scrapyd
   reverse-proxy:
     image: nginx:alpine
     volumes:
       - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
       - "./conf/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro"
     depends_on:
       - scrapyd
     links:
       - scrapyd
     ports:
       - 80:80    

     container_name: scrapyd-web
