version: '3'

services:
   scrapyd:
     image: scrapyd
     container_name: scrapyd
     restart: always

   reverse-proxy:
     image: nginx:alpine
     volumes:
       - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
       - "./conf/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro"
     depends_on:
       - scrapyd
     links:
       - scrapyd
     ports:
       - 80:80    
     restart: always   
     container_name: scrapyd-web

   scrapoxy:
     image: scrapoxy_custom
     links:
       - scrapyd
     ports:
       - 8888:8888
       - 8889:8889
     restart: always
         

